### ISSUE TITLE
Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (83)

### ISSUE THREAD

**Issue by gandarez** [rampatra/wedding-website#13]
Trying to run locally in a macOS Catalina.

```bash
Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (83)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.13.1
    at module.exports (/Users/gandarez/Development/marriage/wedding-website/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/Users/gandarez/Development/marriage/wedding-website/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14)
    at Module.require (internal/modules/cjs/loader.js:964:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/gandarez/Development/marriage/wedding-website/node_modules/gulp-sass/index.js:162:21)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
```

**Comment by lbouriez** [comment]
Did you check this link: https://stackoverflow.com/questions/37415134/error-node-sass-does-not-yet-support-your-current-environment-windows-64-bit-w

**Comment by canaangifford** [comment]
For anyone else, the issue is coming from the gulp-sass dependency.
https://github.com/dlmanning/gulp-sass/issues/779
